/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'CreatePost': ApiRouteHandler<{ title: string; author_id: string; body: string; image_url?: unknown }, ApiResponse<201, { id: string; title: string; body: string; author_id: string }> | ApiResponse<400, { error: string }>, never>
    'GetUser': ApiRouteHandler<{ clerk_user_id: string }, ApiResponse<201, { id: string; clerk_user_id: string; name: string; email: string; avatar_url: unknown; role: string; is_deleted: boolean; created_at: string }> | ApiResponse<400, { error: string }>, never>
    'CreateUser': ApiRouteHandler<{ name: string; clerk_user_id: string; email: string; avatar_url?: unknown }, ApiResponse<201, { clerk_user_id: string; name: string; email: string; avatar_url: unknown }> | ApiResponse<400, { error: string }>, never>
  }
}